.\" This is a comment line, which wont appear in the man page.                                                                    
.TH frico 1
.SH NAME
frico \- Friendly Radiation Integral COde
.SH SYNOPSIS
.B frico
[\fI\,OPTION\/\fR]... 
.SH DESCRIPTION
.PP
A 3D Method of Moments code for the simulation of antennas and scattering
structures.
.PP
This code implements the Method of Moments (MoM) as described in "NASA
Contractor Report 189594" titled "MOM3D Method of Moments Code - Theory
Manual" by John F. Shaeffer.
.PP
The code takes as input a GMSH .geo file and some parameters specifying the
sources and the simulation frequency. The output is written to text files (for
impedance and radiation patterns) and SILO files for the visualization of fields
using VisIt.
.SH OPTIONS
.TP
\fB\-A\fR
Do not use quadratures, use approximate matrix as described in the MOM3D theory
manual.
.TP
\fB\-d\fR
Dump matrices and right hand sides of all the linear systems.
.TP
\fB\-g <path>\fR
Path to the input geometry as .geo file obtained from GMSH.
.TP
\fB\-f <frequency>\fR
Simulation frequency specified in Hz. Exponential notation may be used. Mutually
exclusive with -R.
.TP
\fB\-R <start>:<step>:<end>\fR
Do a sweep from <start> Hz to <end> Hz at steps of <step> Hz. Frequencies may be
specified using exponential notation. Mutually exclusive with -f.
.TP
\fB\-k <order>\fR
Integration order to be used when not in approximate mode (-A). Default is 1.
.TP
\fB\-n <name>\fR
Set a descriptive name for the simulation. Default is "default".
.TP
\fB\-S\fR
Expert stuff: In the current implementation the matrix is slightly nonsymmetric
(only for non-approximate variant) because of the handling of the self elements.
This flag forces symmetrization by doing 0.5*(Z + Z^T). Don't use.
.TP
\fB\-x <list of tags>\fR
List of comma-separated tags corresponding to GMSH surfaces you want to exclude
from loading. This is useful when in your mesh you have edges with more than
two triangles attached, but the option exists only for convenience. The proper
way to do this is to delete surfaces directly in the .geo file, for example:

.in +4n
.EX
SetFactory("OpenCASCADE");
Cylinder(1) = {0, 0, 0, 1, 0, 0, 0.01, 2*Pi};
Cylinder(2) = {-1, 0, 0, 1, 0, 0, 0.01, 2*Pi};
Coherence;
MeshSize{ PointsOf{ Surface{:}; } } = 0.01;
Mesh 2;
Delete { Volume{1,2}; }
Delete { Surface{3}; }
.EE
.in

.SH SEE ALSO
.PP
"NASA Contractor Report 189594" titled "MOM3D Method of Moments Code - Theory
Manual" by John F. Shaeffer.
.PP
You should visit the Friuli Venezia Giulia region in Italy and taste "Frico",
which is one of the main regional dishes.
.SH BUGS
Report bugs to <matteo.cicuttin@polito.it>
.SH AUTHOR
Written by Matteo `IV3IWE` Cicuttin
.SH COPYRIGHT
Copyright (C) 2025-2026 Matteo Cicuttin - Politecnico di Torino

