.\" This is a comment line, which wont appear in the man page.                                                                    
.TH frico 1
.SH NAME
frico \- Friendly Radiation Integral COde
.SH SYNOPSIS
.B frico
[\fI\,OPTION\/\fR]... 
.SH DESCRIPTION
.PP
A 3D Method of Moments code for the simulation of antennas and scattering
structures.
.PP
This code implements the Method of Moments (MoM) as described in "NASA
Contractor Report 189594" titled "MOM3D Method of Moments Code - Theory
Manual" by John F. Shaeffer.
.PP
The code takes as input a GMSH .geo file and some parameters specifying the
sources and the simulation frequency. The output is written to text files (for
impedance and radiation patterns) and SILO files for the visualization of fields
using VisIt.
.SH OPTIONS
.TP
\fB\-A\fR
Do not use quadratures, use approximate matrix as described in the MOM3D theory
manual.
.TP
\fB\-d\fR
Dump matrices and right hand sides of all the linear systems.
.TP
\fB\-e\fR
Force reorientation of basis functions involved in the delta-gap (see CAVEATS).
.TP
\fB\-g <path>\fR
Path to the input geometry as .geo file obtained from GMSH.
.TP
\fB\-f <frequency>\fR
Simulation frequency specified in Hz. Exponential notation may be used. Mutually
exclusive with -R.
.TP
\fB\-s <physgroup>\fR
Currently only antenna simulation is supported, therefore only delta-gap sources
are allowed. Delta-gap voltage is applied to one or more curves that need to be
grouped in a physical group of your GMSH model. For example, if a delta-gap
source on curves 4,5,6 and 7 is wanted, you need to put in your GMSH model
something like

.in +4n
.EX
Physical Curve("source", 10) = {4,5,6,7};
.EE
.in

.TP
\fB\-b\fR
Bistatic Radar Cross Section computation.

.TP
\fB\-m\fR
Monostatic Radar Cross Section computation.

.TP
\fB\-P <plane>:<width>:<height>:<meshsize>\fR \c
.br
\fB\-P <nx>:<ny>:<nz>:<width>:<height>:<meshsize>\fR
Add a field evaluation plane.

.TP
\fB\-p <name>:<x>:<y>:<z>\fR
Add a field probe.

.TP
\fB\-R <start>:<step>:<end>\fR
Do a sweep from <start> Hz to <end> Hz at steps of <step> Hz. Frequencies may be
specified using exponential notation. Mutually exclusive with -f.
.TP
\fB\-k <order>\fR
Integration order to be used when not in approximate mode (-A). Default is 1.
.TP
\fB\-n <name>\fR
Set a descriptive name for the simulation. Default is "default".
.TP
\fB\-S\fR
Expert stuff: In the current implementation the matrix is slightly nonsymmetric
(only for non-approximate variant) because of the handling of the self elements.
This flag forces symmetrization by doing 0.5*(Z + Z^T). Do not use.
.TP
\fB\-x <list of tags>\fR
List of comma-separated tags corresponding to GMSH surfaces you want to exclude
from loading. This is useful when in your mesh you have edges with more than
two triangles attached, but the option exists only for convenience. The proper
way to do this is to delete surfaces directly in the .geo file, for example:

.in +4n
.EX
SetFactory("OpenCASCADE");
Cylinder(1) = {0, 0, 0, 1, 0, 0, 0.01, 2*Pi};
Cylinder(2) = {-1, 0, 0, 1, 0, 0, 0.01, 2*Pi};
Coherence;
MeshSize{ PointsOf{ Surface{:}; } } = 0.01;
Mesh 2;
Delete { Volume{1,2}; }
Delete { Surface{3}; }
.EE
.in

.TP
\fB\-Z <value>\fR
Set system impedance for SWR calculations (default: 50 Ohm) 

.SH CAVEATS
Delta-gap sources can occasionally give some problems. What happens is the
following:
.RS 2
.IP \fBo\fP 4
The delta-gap is applied on a curve between two entities with different tags
.IP
In this case it is assumed (this should be confirmed with GMSH folks) that all
the triangles in the lower-numbered entity have lower tags than the triangles
in the higher-numbered entity. In this case there is no problem, because all
the RWG basis functions are oriented lower-to-higher and therefore all the edges
in the delta-gap will have coherent orientation.
.IP \fBo\fP 4
The delta-gap is applied on curves embedded into a single entity \fBAND\fP the
curves do not form a closed curve.
.IP
In this case the triangles on both sides of the curves will be part of the same
entity, therefore it is not possible to guarantee a coherent orientation of the
involved RWG basis functions. In turn, this makes impossible to know the sign
of the voltage to apply to the edges of the delta-gap. The code employs a
simple algorithm that checks the orientation of adjacent basis functions, and
reorients them if it is incoherent. The algorithm works in most cases, but its
robustness w.r.t. real-world geometries has not been thoroughly tested.
.IP \fBo\fP 4
Fancier cases
.IP
Not explicitly supported for now, therefore YMMV. Please file a bug describing
your situation.
.RE
.PP
Be aware of this issue if you get nonsensical results when using delta-gaps.
This situation can be easily detected by eye by using the "Label" plot in VisIt
to inspect the numbering of the elements across the delta-gap.

.SH SEE ALSO
The required theory to understand this code and MoM in general is contained in
.RS 2
.IP \fBo\fP 4
"Field Computations by Moment Methods" by Roger F. Harrington.
.IP \fBo\fP 4
"NASA Contractor Report 189594" titled "MOM3D Method of Moments Code - Theory
Manual" by John F. Shaeffer.
.IP \fBo\fP 4
"The Method of Moments in Electromagnetics" by K4LLA Walton C. Gibson.
.RE
.PP
You should visit the Friuli Venezia Giulia region in Italy and taste "Frico",
which is one of the main regional dishes.
.SH BUGS
Report bugs to <matteo.cicuttin@polito.it>
.SH AUTHOR
Written by IV3IWE Matteo Cicuttin
.SH COPYRIGHT
Copyright (C) 2025-2026 Matteo Cicuttin - Politecnico di Torino

